import { defineStore } from 'pinia';

export const useTourStore = defineStore('tours', {
  state: () => ({
    tours: [
      {
        id: 0,
        title: 'Bangkok',
        visited: 45,
        ordered: 50,
        favorite: 320,
        feedback: 15,
        stars: 4,
        adultPrice: 100,
        infantPrice: 35,
        infantAge: '3-9',
        timeDuration: 8,
        count: 70,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn2p3xRAPsZDtCigNjp5Zi7FP5hHxErTcUuQ&s',
      },
      {
        id: 1,
        title: 'Antalya',
        visited: 65,
        ordered: 75,
        favorite: 250,
        feedback: 12,
        stars: 5,
        adultPrice: 110,
        infantPrice: 40,
        infantAge: '3-9',
        timeDuration: 10,
        count: 75,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOL98pqF2MzI7lcvMinp7vAJiPzLulIt-FVBTd55tfzGBRl7_L5bd0THOFqNK0KBeBU5Y&usqp=CAU',
      },
      {
        id: 2,
        title: 'Phuket',
        visited: 50,
        ordered: 60,
        favorite: 300,
        feedback: 18,
        stars: 3,
        adultPrice: 95,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 9,
        count: 65,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP5Yrvn1x90IuKpYBvlgXvCT6YCSfQ5pugdd1VofRIAarZ4DJx8OsV37vDIkm1LgO6CdE&usqp=CAU',
      },
      {
        id: 3,
        title: 'Izmir',
        visited: 70,
        ordered: 80,
        favorite: 270,
        feedback: 20,
        stars: 4,
        adultPrice: 105,
        infantPrice: 41,
        infantAge: '3-9',
        timeDuration: 12,
        count: 80,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ884jJbvwORnX_olEtxP33S1YfwUl-PLlRiPzjuiKVvr_o6sHMGA-7Dy1vDj1ebdkf9o0&usqp=CAU',
      },
      {
        id: 4,
        title: 'Chiang Mai',
        visited: 55,
        ordered: 65,
        favorite: 310,
        feedback: 13,
        stars: 5,
        adultPrice: 99,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 7,
        count: 68,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTadg1sgXPM7Dwax9XSatftPauY9ym2XNiJlEaG9ZkIGQLcX2kmX7yW8NQqepnjI7MVa28&usqp=CAU',
      },
      {
        id: 5,
        title: 'Bursa',
        visited: 63,
        ordered: 70,
        favorite: 200,
        feedback: 14,
        stars: 3,
        adultPrice: 108,
        infantPrice: 37,
        infantAge: '3-9',
        timeDuration: 9,
        count: 73,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-05wq7Vl-FES8TT3EheJ2VCIaoat6LQIR6Q&s',
      },
      {
        id: 6,
        title: 'Pattaya',
        visited: 40,
        ordered: 55,
        favorite: 320,
        feedback: 16,
        stars: 4,
        adultPrice: 105,
        infantPrice: 36,
        infantAge: '3-9',
        timeDuration: 8,
        count: 70,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDcVv-0cfBppcoFac0IXy6TSbfYg8X_KYxGg&s',
      },
      {
        id: 7,
        title: 'Ankara',
        visited: 75,
        ordered: 78,
        favorite: 260,
        feedback: 10,
        stars: 5,
        adultPrice: 115,
        infantPrice: 42,
        infantAge: '3-9',
        timeDuration: 11,
        count: 77,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8ov8sRhM64d1tCx4L7eMO9g5YxgTVHN7Wmg&s',
      },
      {
        id: 8,
        title: 'Hua Hin',
        visited: 47,
        ordered: 60,
        favorite: 325,
        feedback: 12,
        stars: 4,
        adultPrice: 106,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 7,
        count: 66,
        type: 'Группавая',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDzz8D241URzRwI-62aB8bD-XalSmStjxi4w&s',
      },
      {
        id: 9,
        title: 'Istanbul',
        visited: 68,
        ordered: 75,
        favorite: 230,
        feedback: 17,
        stars: 3,
        adultPrice: 109,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 10,
        count: 72,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      },
      {
        id: 10,
        title: 'Ayutthaya',
        visited: 42,
        ordered: 54,
        favorite: 310,
        feedback: 14,
        stars: 5,
        adultPrice: 104,
        infantPrice: 40,
        infantAge: '3-9',
        timeDuration: 9,
        count: 70,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1557166086-184bcb380d9c',
      },
      {
        id: 11,
        title: 'Gaziantep',
        visited: 60,
        ordered: 65,
        favorite: 210,
        feedback: 13,
        stars: 4,
        adultPrice: 97,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 8,
        count: 64,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 12,
        title: 'Krabi',
        visited: 35,
        ordered: 49,
        favorite: 300,
        feedback: 18,
        stars: 3,
        adultPrice: 101,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 8,
        count: 67,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
      {
        id: 13,
        title: 'Mardin',
        visited: 72,
        ordered: 78,
        favorite: 240,
        feedback: 20,
        stars: 5,
        adultPrice: 114,
        infantPrice: 42,
        infantAge: '3-9',
        timeDuration: 12,
        count: 77,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0',
      },
      {
        id: 14,
        title: 'Trang',
        visited: 45,
        ordered: 57,
        favorite: 330,
        feedback: 15,
        stars: 4,
        adultPrice: 98,
        infantPrice: 37,
        infantAge: '3-9',
        timeDuration: 9,
        count: 66,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 15,
        title: 'Konya',
        visited: 65,
        ordered: 70,
        favorite: 220,
        feedback: 12,
        stars: 3,
        adultPrice: 96,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 8,
        count: 70,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      },
      {
        id: 16,
        title: 'Phang Nga',
        visited: 39,
        ordered: 53,
        favorite: 310,
        feedback: 17,
        stars: 4,
        adultPrice: 102,
        infantPrice: 36,
        infantAge: '3-9',
        timeDuration: 7,
        count: 68,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
      {
        id: 17,
        title: 'Adana',
        visited: 70,
        ordered: 75,
        favorite: 260,
        feedback: 19,
        stars: 5,
        adultPrice: 107,
        infantPrice: 40,
        infantAge: '3-9',
        timeDuration: 11,
        count: 74,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1557166086-184bcb380d9c',
      },
      {
        id: 18,
        title: 'Koh Samui',
        visited: 48,
        ordered: 62,
        favorite: 320,
        feedback: 16,
        stars: 3,
        adultPrice: 103,
        infantPrice: 37,
        infantAge: '3-9',
        timeDuration: 9,
        count: 69,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0',
      },
      {
        id: 19,
        title: 'Eskisehir',
        visited: 55,
        ordered: 68,
        favorite: 230,
        feedback: 14,
        stars: 4,
        adultPrice: 106,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 10,
        count: 71,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 20,
        title: 'Kanchanaburi',
        visited: 40,
        ordered: 54,
        favorite: 310,
        feedback: 18,
        stars: 5,
        adultPrice: 99,
        infantPrice: 35,
        infantAge: '3-9',
        timeDuration: 8,
        count: 67,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
      {
        id: 21,
        title: 'Sanliurfa',
        visited: 60,
        ordered: 66,
        favorite: 210,
        feedback: 13,
        stars: 3,
        adultPrice: 110,
        infantPrice: 42,
        infantAge: '3-9',
        timeDuration: 9,
        count: 74,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      },
      {
        id: 22,
        title: 'Nakhon Ratchasima',
        visited: 35,
        ordered: 50,
        favorite: 300,
        feedback: 19,
        stars: 4,
        adultPrice: 108,
        infantPrice: 36,
        infantAge: '3-9',
        timeDuration: 7,
        count: 65,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1557166086-184bcb380d9c',
      },
      {
        id: 23,
        title: 'Van',
        visited: 72,
        ordered: 80,
        favorite: 240,
        feedback: 20,
        stars: 5,
        adultPrice: 111,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 12,
        count: 77,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 24,
        title: 'Rayong',
        visited: 50,
        ordered: 60,
        favorite: 320,
        feedback: 16,
        stars: 3,
        adultPrice: 102,
        infantPrice: 37,
        infantAge: '3-9',
        timeDuration: 8,
        count: 70,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
      {
        id: 25,
        title: 'Mugla',
        visited: 65,
        ordered: 72,
        favorite: 250,
        feedback: 18,
        stars: 4,
        adultPrice: 112,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 10,
        count: 73,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0',
      },
      {
        id: 26,
        title: 'Trat',
        visited: 47,
        ordered: 57,
        favorite: 310,
        feedback: 15,
        stars: 5,
        adultPrice: 98,
        infantPrice: 36,
        infantAge: '3-9',
        timeDuration: 9,
        count: 68,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 27,
        title: 'Mersin',
        visited: 75,
        ordered: 78,
        favorite: 260,
        feedback: 14,
        stars: 3,
        adultPrice: 108,
        infantPrice: 40,
        infantAge: '3-9',
        timeDuration: 11,
        count: 74,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      },
      {
        id: 28,
        title: 'Sukhothai',
        visited: 40,
        ordered: 52,
        favorite: 315,
        feedback: 13,
        stars: 4,
        adultPrice: 104,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 8,
        count: 68,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1557166086-184bcb380d9c',
      },
      {
        id: 29,
        title: 'Malatya',
        visited: 68,
        ordered: 76,
        favorite: 230,
        feedback: 19,
        stars: 5,
        adultPrice: 109,
        infantPrice: 42,
        infantAge: '3-9',
        timeDuration: 10,
        count: 72,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1527515637467-2d0ef3a1a6a3',
      },
      {
        id: 30,
        title: 'Surat Thani',
        visited: 52,
        ordered: 63,
        favorite: 320,
        feedback: 17,
        stars: 4,
        adultPrice: 101,
        infantPrice: 37,
        infantAge: '3-9',
        timeDuration: 9,
        count: 67,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
      {
        id: 31,
        title: 'Denizli',
        visited: 60,
        ordered: 66,
        favorite: 210,
        feedback: 14,
        stars: 3,
        adultPrice: 95,
        infantPrice: 41,
        infantAge: '3-9',
        timeDuration: 8,
        count: 64,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0',
      },
      {
        id: 32,
        title: 'Buriram',
        visited: 41,
        ordered: 54,
        favorite: 320,
        feedback: 19,
        stars: 4,
        adultPrice: 98,
        infantPrice: 39,
        infantAge: '3-9',
        timeDuration: 9,
        count: 70,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1557166086-184bcb380d9c',
      },
      {
        id: 33,
        title: 'Aydin',
        visited: 64,
        ordered: 68,
        favorite: 240,
        feedback: 11,
        stars: 2,
        adultPrice: 103,
        infantPrice: 38,
        infantAge: '3-9',
        timeDuration: 11,
        count: 72,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1493558103817-58b2924bce98',
      },
      {
        id: 34,
        title: 'Phetchaburi',
        visited: 49,
        ordered: 60,
        favorite: 310,
        feedback: 14,
        stars: 5,
        adultPrice: 109,
        infantPrice: 36,
        infantAge: '3-9',
        timeDuration: 10,
        count: 73,
        type: 'Группавая',
        img: 'https://images.unsplash.com/photo-1529238062291-7932f7d47fa3',
      },
    ],
  }),
});
